export default { 
  label_small: 11, 
  label_medium: 12, 
  body_small: 12, 
  title_small: 14, 
  label_large: 14, 
  body_medium: 14, 
  title_medium: 16, 
  body_large: 16, 
  title_large: 22, 
  headline_small: 24, 
  headline_medium: 28, 
  headline_large: 32, 
  display_small: 36, 
  display_medium: 45, 
  display_large: 57, 
}